apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: university-dtg
  annotations:
    fluxcd.io/automated: "false"
  namespace: university-ns
spec:
  releaseName: university-dtg
  chart:
    path: platforms/hyperledger-indy/charts/indy-domain-genesis
    git: https://github.com/mramprasad-os/blockchain-automation-framework.git
    ref: develop
  values:
    metadata:
      name: university-dtg
      namespace: university-ns
    organization:
      name: university
    configmap:
      domainGenesis: |-
        {"reqSignature":{},"txn":{"data":{"alias":"authority-trustee","dest":"Vo6Pp87doP82kEboACB9Et","role":"0","verkey":"GhFw3S3XpFScqbMRHU54ihXMJ6tipv3xWqd69sdqpGLa"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":1},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-steward-1","dest":"Q41RMW6dtXVFJgMcw2wgWq","role":"2","verkey":"DZiSCz4Rk7miLbn1unSNUegZruZHcvzfJeV8whugL71w"},"metadata":{"from":"Vo6Pp87doP82kEboACB9Et"},"type":"1"},"txnMetadata":{"seqNo":2},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-steward-2","dest":"41REkX8muysPgJkE6N1e56","role":"2","verkey":"2e4hCRXshWanyKBZt9anD1DXJPnVB46ZC41jtGNwWFs3"},"metadata":{"from":"Vo6Pp87doP82kEboACB9Et"},"type":"1"},"txnMetadata":{"seqNo":3},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-steward-3","dest":"2C5TkRFz3jy8f3Z5WCJ2oH","role":"2","verkey":"eef8uQ4TPhsAaJLZFP1fXmjQpNPkrzgW52bd7yzPDAi"},"metadata":{"from":"Vo6Pp87doP82kEboACB9Et"},"type":"1"},"txnMetadata":{"seqNo":4},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-steward-4","dest":"PeJMc6gkaU46LXUmCLf3dz","role":"2","verkey":"DLnyhmrSXUWnCwmhD1Az7Syst5YVrXkMsMgUKV7QpJvC"},"metadata":{"from":"Vo6Pp87doP82kEboACB9Et"},"type":"1"},"txnMetadata":{"seqNo":5},"ver":"1"}
