apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: provider-provider-endorser-transaction
  annotations:
    fluxcd.io/automated: "false"
  namespace: provider-ns
spec:
  releaseName: provider-provider-endorser-transaction
  chart:
    path: platforms/hyperledger-indy/charts/indy-ledger-txn
    git: https://github.com/mramprasad-os/blockchain-automation-framework.git
    ref: develop
  values:
    metadata:
      name: provider-provider-endorser-transaction
      namespace: provider-ns
    network:
      name: baf
    image:
      cli:
        name: provider
        repository: index.docker.io/hyperledgerlabs/indy-ledger-txn:latest
        pullSecret: regcred
    vault:
      address: http://10.1.3.82:8200
      role: rw
      serviceAccountName: provider-admin-vault-auth
      auth_path: kubernetes-provider-admin-auth
    organization:
      name: provider
      adminIdentity:
        name: authority-trustee
        did: Vo6Pp87doP82kEboACB9Et
        path: authority/trustees
      newIdentity:
        name: provider-endorser
        role: ENDORSER
        did: NzaWnTAt38H8nuS3jBAnyV
        verkey: CzEXiJowW5pyhVPa6Zrpw7jckc6ScramYyYqyqNb18xp
        path: provider/endorsers
    node:
      name: provider
