apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: provider-provider-trustee
  annotations:
    fluxcd.io/automated: "false"
  namespace: provider-ns
spec:
  releaseName: provider-provider-trustee
  chart:
    path: platforms/hyperledger-indy/charts/indy-key-mgmt
    git: https://github.com/mramprasad-os/blockchain-automation-framework.git
    ref: develop
  values:
    metadata:
      name: provider-provider-trustee
      namespace: provider-ns
    network:
      name: baf
    image:
      name: provider
      repository: index.docker.io/hyperledgerlabs/indy-key-mgmt:1.11.0
      pullSecret: regcred
    vault:
      address: http://10.1.3.82:8200
      keyPath: provider.trustees
      identity: provider-trustee
      auth_path: kubernetes-provider-admin-auth
    account:
      service: provider-admin-vault-auth
      role: rw
