apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: university-endorser
  annotations:
    fluxcd.io/automated: "false"
  namespace: university-ns
spec:
  releaseName: university-endorser-faber
  chart:
    path: examples/identity-app/charts/faber
    git: https://github.com/mramprasad-os/blockchain-automation-framework.git
    ref: develop
  values:
    metadata:
      namespace: university-ns
      name: university-endorser
    organization:
      name: university
    image:
      pullSecret: regcred
      init:
        name: certs-init
        repository: alpine:3.9.4
      agent:
        name: university-endorser
        repository: index.docker.io/garyanti/aries-agents:1.11.0
    service:
      ports: 
        service: 15033
        endpoint: 15034
        webhook: 15035
      
      address: university-endorser.baf.blockchpoc.com
      
      ledger: http://authority-webserver.baf.blockchpoc.com:15010
      genesis: http://authority-webserver.baf.blockchpoc.com:15010/genesis
    vault:
      address: http://10.1.3.82:8200
      serviceAccountName: university-university-endorser-vault-auth
      authPath: kubernetes-university-university-endorser-auth
      endorserName: university-endorser
      role: ro
    storage:
      size: 128Mi
      className: university-azure-storageclass
    proxy:
      
      provider: "ambassador"
